backend:
  image:
    repository: flauw/realworld-backend
    tag: latest
  port: 3000
  env:
    DATABASE_URL: postgresql://realworld:realworld@realworld-db:5432/realworld
  replicaCount: 2

frontend:
  image:
    repository: flauw/realworld-frontend
    tag: latest
  port: 4100
  env:
    REACT_APP_API_URL: http://realworld-backend:3000/api
  replicaCount: 2

db:
  image:
    repository: postgres
    tag: "16"
  port: 5432
  user: realworld
  password: realworld
  name: realworld

ingress:
  enabled: true
  ingressClassName: traefik-ingress
  hosts:
    - host: app-pfw.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - app-pfw.duckdns.org
      secretName: app-tls
