---

backend:
  image:
    repository: flauw/realworld-backend
    tag: latest
  port: 3000
  env:
    DATABASE_URL: postgresql://realworld:realworld@realworld-db:5432/realworld
    JWT_SECRET: supersecretjwtkey
  replicaCount: 2

frontend:
  image:
    repository: flauw/realworld-frontend
    tag: latest
  port: 4100
  env:
    REACT_APP_API_URL: /api
  replicaCount: 2

db:
  image:
    repository: postgres
    tag: "16"
  port: 5432
  user: realworld
  password: realworld
  name: realworld
  persistence:
    size: 1Gi

ingress:
  enabled: true
  ingressClassName: traefik-ingress
  hosts:
    - host: app-pfw.duckdns.org
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls:
    - hosts:
        - app-pfw.duckdns.org
      secretName: app-tls