---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-db
  template:
    metadata:
      labels:
        app: realworld-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.port }}
          envFrom:
            - secretRef:
                name: realworld-db-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: realworld-db-pvc
