---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realworld-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | default "1Gi" }}
