---

apiVersion: v1
kind: Service
metadata:
  name: realworld-db
spec:
  type: ClusterIP
  selector:
    app: realworld-db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}