apiVersion: v1
kind: Service
metadata:
  name: realworld-backend
spec:
  type: ClusterIP
  selector:
    app: realworld-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
