apiVersion: v1
kind: Service
metadata:
  name: realworld-frontend
spec:
  type: ClusterIP
  selector:
    app: realworld-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
