apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-frontend
  labels:
    app: realworld-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: realworld-frontend
  template:
    metadata:
      labels:
        app: realworld-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: REACT_APP_API_URL
              value: "{{ .Values.frontend.env.REACT_APP_API_URL }}"
