{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realworld
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realworld-frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
